In [21]:
from utils import intersection_over_union

In [18]:
import torch
a = torch.tensor([1,1,0,1,0])

b = torch.cumsum(a, dim=0)/1

b

tensor([1., 2., 2., 3., 3.])

In [20]:
torch.cat((torch.tensor([]), b))

tensor([2., 1., 2., 2., 3., 3.])

In [2]:
import torch
import numpy as np
b1 = np.array(
    [
        [4,5,8,10]
    ]
)
b2 = np.array(
    [
        [5,3,8,10]
    ]
)
box1 = torch.from_numpy(b1)
box2 = torch.from_numpy(b2)

intersection_over_union(box1, box2, box_format="corners")


Intersection Area: tensor([[15.]]) 
 Box1 Area: tensor([[20]], dtype=torch.int32) 
 Box2 Area: tensor([[21]], dtype=torch.int32) 
 Union Area: tensor([[26.]])


tensor([[0.5769]])

In [9]:
import cv2

# Load the image
image = cv2.imread('car.jpg')
# Resize the image to a specific width and height
resized_image = cv2.resize(image, (840, 640))
# Create a window with the specified size
cv2.namedWindow('Bounding Box', cv2.WINDOW_NORMAL)
cv2.resizeWindow('Bounding Box', 840, 640)
# Define the bounding box coordinates
x1, y1 = 1750, 1440  # Top-left corner
x2, y2 = 3750, 2340  # Bottom-right corner

# Draw the bounding box on the image
cv2.rectangle(image, (x1, y1), (x2, y2), (0, 0, 255), 4)

# Display the image
cv2.imshow('Bounding Box', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
import cv2
import numpy as np

# Load YOLO network
net = cv2.dnn.readNet('yolov3.weights', 'yolov3.cfg')

# Load class labels
classes = []
with open('coco.names', 'r') as f:
    classes = [line.strip() for line in f.readlines()]

In [40]:
# Load image
image = cv2.imread('car.jpg')
image = cv2.resize(image, (840, 640))
# Prepare input blob
blob = cv2.dnn.blobFromImage(image, 1/255.0, (416, 416), swapRB=True, crop=False)

# Set the input blob to the network
net.setInput(blob)

# Forward pass through the network to get detections
output_layers_names = net.getUnconnectedOutLayersNames()
layer_outputs = net.forward(output_layers_names)

# Process the output detections
for output in layer_outputs:
    for detection in output:
        scores = detection[5:]
        class_id = np.argmax(scores)
        confidence = scores[class_id]

        if confidence > 0.5:  # Set a minimum confidence threshold
            # Get the bounding box coordinates
            center_x = int(detection[0] * image.shape[1])
            center_y = int(detection[1] * image.shape[0])
            width = int(detection[2] * image.shape[1])
            height = int(detection[3] * image.shape[0])

            # Calculate top-left corner coordinates of the bounding box
            x = int(center_x - width / 2)
            y = int(center_y - height / 2)

            # Draw the bounding box and label on the image
            cv2.rectangle(image, (x, y), (x + width, y + height), (0, 255, 0), 2)
            label = f'{classes[class_id]}: {confidence:.2f}'
            cv2.putText(image, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX,0.5, (0, 255, 0), 2)
        


In [41]:
# Create a window with the specified size
cv2.namedWindow('Bounding Box', cv2.WINDOW_NORMAL)
cv2.resizeWindow('Bounding Box', 840, 640)
cv2.imshow('Bounding Box', image)
cv2.waitKey(0)
cv2.destroyAllWindows()